# Generated by Django 4.2.6 on 2023-10-15 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pelis_crud', '0002_remove_pelicula_año_lanzamiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='usuario',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='pelis_crud.usuario'),
        ),
    ]
